def test_root(client):
    res = client.get("/")
    assert res.status_code == 200
    assert res.json()["message"] == "hello from docker"


def test_create_user(client):
    user_data = {
        "email": "test@example.com",
        "password": "testpassword"
    }

    res = client.post("/users/", json=user_data)

    assert res.status_code == 201
    assert res.json()["email"] == "test@example.com"
    assert "password" not in res.json()

def test_user_isolation(client):
    res = client.get("/users/999999")
    assert res.status_code == 404

from app import models
from app.database import sessionLocal

def test_user_rollback():
    db = sessionLocal()
    try:
        user = db.query(models.User).filter(
            models.User.email == "test@example.com"
        ).first()
        assert user is None
    finally:
        db.close()


def test_get_user(client):
    # First, create a user
    user_data = {
        "email": "getuser@example.com",
        "password": "testpassword"
    }

    create_res = client.post("/users/", json=user_data)

    assert create_res.status_code == 201

    # Extract the ID generated by PostgreSQL
    user_id = create_res.json()["id"]

    # Now retrieve that user
    res = client.get(f"/users/{user_id}")

    assert res.status_code == 200
    assert res.json()["id"] == user_id
    assert res.json()["email"] == "getuser@example.com"

def test_get_nonexistent_user(client):
    """
    Request a user ID that does not exist.

    The API should return 404 Not Found rather than crashing
    or returning an empty response.
    """
    response = client.get("/users/999999")

    assert response.status_code == 404


def test_create_user_missing_fields(client):
    """
    Check request validation.

    Email and password are required by the UserCreate schema.
    Sending an incomplete request should return 422.
    """
    response = client.post(
        "/users/",
        json={"email": "missingpassword@example.com"}
    )

    assert response.status_code == 422


def test_create_user_invalid_email(client):
    """
    Check that Pydantic rejects an invalid email format.

    This test applies if your UserCreate schema uses EmailStr.
    If your schema only uses str, this validation may not exist.
    """
    response = client.post(
        "/users/",
        json={
            "email": "not-an-email",
            "password": "testpassword"
        }
    )

    assert response.status_code == 422